---
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
  yarn: true
before_deploy: yarn build
deploy:
  fqdn: jelena.wedding
  github_token: $GITHUB_TOKEN
  local-dir: build
  provider: pages
  skip_cleanup: true
  target-branch: gh-pages
  true:
    branch: master
